# Generated by Django 5.0.2 on 2024-03-14 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobindustry_industryname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='jobIndustry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jobIndustry', to='jobs.jobindustry'),
        ),
    ]
