# Generated by Django 5.0.2 on 2024-03-15 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_jobmodel_jobindustry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='filter_industry',
        ),
        migrations.RemoveField(
            model_name='jobmodel',
            name='filter_job_type',
        ),
        migrations.RemoveField(
            model_name='jobmodel',
            name='filter_location',
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='jobIndustry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobIndustry', to='jobs.jobindustry'),
        ),
    ]
