# Generated by Django 5.0.1 on 2024-03-14 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_jobmodel_jobindustry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='jobIndustry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobIndustry', to='jobs.jobindustry'),
        ),
    ]
