# Generated by Django 5.0.1 on 2024-03-14 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_jobmodel_jobindustry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='filter_industry',
        ),
        migrations.RemoveField(
            model_name='jobmodel',
            name='filter_job_type',
        ),
        migrations.RemoveField(
            model_name='jobmodel',
            name='filter_location',
        ),
        migrations.RemoveField(
            model_name='jobmodel',
            name='jobIndustry',
        ),
        migrations.AddField(
            model_name='jobindustry',
            name='jobs',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='jobIndustry', to='jobs.jobmodel'),
        ),
    ]
