# Generated by Django 5.0.2 on 2024-03-25 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_jobmodel_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.TextField()),
                ('status', models.CharField(choices=[('IN REVIEW', 'in review'), ('APPROVED', 'approved'), ('DENIED', 'denied')], default='in review', max_length=20)),
                ('jobId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='jobs.jobmodel')),
            ],
        ),
    ]
