# Generated by Django 5.0.2 on 2024-03-26 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_rename_job_applicationmodel_jobid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationmodel',
            old_name='jobId',
            new_name='job',
        ),
    ]
