# Generated by Django 5.0.2 on 2024-03-26 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_rename_jobid_applicationmodel_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationmodel',
            old_name='job',
            new_name='job_Id',
        ),
    ]
