# Generated by Django 5.0.2 on 2024-03-26 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_remove_applicationmodel_jobid_applicationmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='applications',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.applicationmodel'),
        ),
    ]
