# Generated by Django 5.0.2 on 2024-03-26 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_remove_jobmodel_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_application', to='jobs.jobmodel'),
        ),
    ]
