# Generated by Django 5.0.2 on 2024-03-13 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_usermodel_userage_usermodel_usercountry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='userAge',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='userCountry',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='userType',
        ),
    ]
